language: node_js


node_js:
- iojs
- '7'


addons:
  ssh_known_hosts:
  - 104.189.109.222


before_install:
- sudo apt-get update -qq


install:
- wget https://github.com/mattschaller/home-assistant/archive/0.1.0.tar.gz -O /tmp/hass.tar.gz
- tar -xvf /tmp/hass.tar.gz
- export PATH=$PATH:$PWD/home-assistant-0.1.0/bin/

before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ matt@104.189.109.222:/home/matt/travis/
  on:
    branch: master
